#!/bin/bash

echo "🚀 Railway MySQL 数据库初始化脚本"
echo "=================================="
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 首先连接到数据库："
echo "   mysql -hnozomi.proxy.rlwy.net -P30005 -uroot -p railway"
echo ""
echo "2. 当提示输入密码时，粘贴："
echo "   JohUDizCHzjAQIVxdNgyrUfVSMKesqPH"
echo ""
echo "3. 连接成功后，运行："
echo "   source /Users/apple/Desktop/project-1500/backend-api/init-railway-mysql.sql;"
echo ""
echo "4. 或者使用管道命令（一行执行）："
echo "   mysql -hnozomi.proxy.rlwy.net -P30005 -uroot -pJohUDizCHzjAQIVxdNgyrUfVSMKesqPH railway < /Users/apple/Desktop/project-1500/backend-api/init-railway-mysql.sql"
echo ""
echo "=================================="
echo ""
echo "提示：如果连接失败，可能是网络问题，请稍后重试。"